//! Safe ordered workspace bootstrap reconciliation.

use std::path::{Path, PathBuf};

use crate::{TargetKind, WorkspaceFileSystem, WorkspaceModel, XtaskError};

const GENERATED_MARKER: &str = "// @generated by cargo xtask bootstrap\n";

/// Reconciliation behavior.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ReconcileMode {
    /// Atomically apply every planned change.
    Apply,
    /// Fail silently on drift without writes.
    Check,
    /// Return ordered changes without writes.
    DryRun,
}

/// One ordered non-destructive bootstrap change.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Change {
    /// Create a missing managed file.
    Create {
        /// Destination path.
        path: PathBuf,
        /// Complete generated content.
        content: String,
    },
    /// Replace a generated file only.
    ReplaceGenerated {
        /// Destination path.
        path: PathBuf,
        /// Complete replacement content.
        content: String,
    },
    /// Structurally edit root workspace membership.
    EditRootManifest {
        /// Root manifest path.
        path: PathBuf,
        /// Preserved manifest with modeled membership.
        content: String,
    },
}

impl Change {
    fn path(&self) -> &Path {
        match self {
            Self::Create { path, .. }
            | Self::ReplaceGenerated { path, .. }
            | Self::EditRootManifest { path, .. } => path,
        }
    }

    fn content(&self) -> &str {
        match self {
            Self::Create { content, .. }
            | Self::ReplaceGenerated { content, .. }
            | Self::EditRootManifest { content, .. } => content,
        }
    }

    const fn order(&self) -> u8 {
        match self {
            Self::Create { .. } => 0,
            Self::ReplaceGenerated { .. } => 1,
            Self::EditRootManifest { .. } => 2,
        }
    }
}

/// Canonically ordered bootstrap plan.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ChangeSet {
    /// Ordered changes.
    pub changes: Vec<Change>,
}

/// Plans missing or stale generated entry points without deleting files.
///
/// # Errors
///
/// Returns an error when modeled files cannot be read.
pub fn plan_bootstrap(
    fs: &impl WorkspaceFileSystem,
    root: &Path,
    model: WorkspaceModel,
) -> Result<ChangeSet, XtaskError> {
    let base = if root == Path::new(".") {
        Path::new("")
    } else {
        root
    };
    let root_manifest = base.join("Cargo.toml");
    let root_contents = fs.read(&root_manifest)?.unwrap_or_default();
    let mut changes = Vec::new();
    if !root_contents.contains("members = [\"crates/*\", \"xtask\"]") {
        let mut content = root_contents;
        if !content.ends_with('\n') && !content.is_empty() {
            content.push('\n');
        }
        content.push_str("members = [\"crates/*\", \"xtask\"]\n");
        changes.push(Change::EditRootManifest {
            path: root_manifest,
            content,
        });
    }

    for spec in model.crates.iter().filter(|spec| spec.path != ".") {
        let manifest = base.join(spec.manifest);
        if fs.read(&manifest)?.is_none() {
            changes.push(Change::Create {
                path: manifest,
                content: expected_manifest(spec.name),
            });
        }
        let source_name = if spec.target == TargetKind::Binary {
            "src/main.rs"
        } else {
            "src/lib.rs"
        };
        let source = base.join(spec.path).join(source_name);
        let desired = expected_source(spec.target);
        match fs.read(&source)? {
            None => changes.push(Change::Create {
                path: source,
                content: desired,
            }),
            Some(existing) if existing.starts_with(GENERATED_MARKER) && existing != desired => {
                changes.push(Change::ReplaceGenerated {
                    path: source,
                    content: desired,
                });
            }
            Some(_) => {}
        }
    }
    changes.sort_by(|left, right| {
        left.path()
            .cmp(right.path())
            .then_with(|| left.order().cmp(&right.order()))
    });
    Ok(ChangeSet { changes })
}

/// Plans then optionally applies bootstrap reconciliation.
///
/// # Errors
///
/// Returns an error on drift in check mode or any filesystem failure.
pub fn reconcile(
    fs: &impl WorkspaceFileSystem,
    root: &Path,
    model: WorkspaceModel,
    mode: ReconcileMode,
) -> Result<ChangeSet, XtaskError> {
    let plan = plan_bootstrap(fs, root, model)?;
    match mode {
        ReconcileMode::Apply => {
            for change in &plan.changes {
                fs.write_atomic(change.path(), change.content())?;
            }
            Ok(plan)
        }
        ReconcileMode::Check if !plan.changes.is_empty() => Err(XtaskError::Bootstrap(
            "workspace bootstrap drift detected".into(),
        )),
        ReconcileMode::Check | ReconcileMode::DryRun => Ok(plan),
    }
}

pub(crate) fn check(root: &Path) -> Result<(), XtaskError> {
    reconcile(
        &crate::HostFileSystem,
        root,
        crate::workspace_model(),
        ReconcileMode::Check,
    )
    .map(|_| ())
}

fn expected_source(target: TargetKind) -> String {
    let body = match target {
        TargetKind::Binary => "fn main() {}\n",
        TargetKind::Library | TargetKind::ProcMacro => "//! Generated workspace crate.\n",
    };
    format!("{GENERATED_MARKER}{body}")
}

fn expected_manifest(package: &str) -> String {
    format!(
        "# @generated by cargo xtask bootstrap\n[package]\nname = \"{package}\"\nversion.workspace = true\nedition.workspace = true\n"
    )
}
